using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WordGenerator : MonoBehaviour
{


    // Start is called before the first frame update
    void Start()
    {

    }

    public String GetWord()
    {
        words[
            "Abroad"; "Casual"; "Around"; "Couple";
            "Accept"; "Caught"; "Arrive"; "Course";
            "Access"; "Centre"; "Artist"; "Covers";
            "Across"; "Aspect"; "Create";
            "Acting"; "Chance"; "Assess"; "Credit";
            "Action"; "Change"; "Assist"; "Crisis";
            "Active"; "Charge"; "Assume"; "Custom";
            "Actual"; "Choice"; "Attack"; "Damage";
            "Advice"; "Choose"; "Attend"; "Danger";
            "Advise"; "Chosen"; "August"; "Dealer";
            "Affect"; "Church"; "Author"; "Debate";
            "Afford"; "Circle"; "Avenue"; "Decade";
            "Afraid"; "Client"; "Backed"; "Decide";
            "Agency"; "Closed"; "Barely"; "Defeat";
            "Agenda"; "Closer"; "Battle"; "Defend";
            "Almost"; "Coffee"; "Beauty"; "Define";
            "Always"; "Column"; "Became"; "Degree";
            "Amount"; "Combat"; "Become"; "Demand";
            "Animal"; "Coming"; "Before"; "Depend";
            "Annual"; "Common"; "Behalf"; "Deputy";
            "Answer"; "Comply"; "Behind"; "Desert";
            "Anyone"; "Copper"; "Belief"; "Design";
            "Anyway"; "Corner"; "Belong"; "Desire";
            "Appeal"; "Costly"; "Beaker"; "Detail";
            "Appear"; "County"; "Better"; "Detect";
            "Beyond"; "Budget"; "During"; "Device";
            "Bishop"; "Burden"; "Easily"; "Differ";
            "Border"; "Bureau"; "Eating"; "Dinner";
            "Bottle"; "Button"; "Editor"; "Direct";
            "Bottom"; "Camera"; "Effect"; "Doctor";
            "Bought"; "Cancer"; "Effort"; "Dollar";
            "Branch"; "Cactus"; "Eighth"; "Domain";
            "Breath"; "Carbon"; "Either"; "Double";
            "Bridge"; "Career"; "Eleven"; "Driven";
            "Bright"; "Castle"; "Emerge"; "Driver";
            "Easily"; "Eating"; "Editor"; "Effect";
            "Effort"; "Eighth"; "Either"; "Eleven";
            "Emerge"; "Empire"; "Employ"; "Enable";
            "Ending"; "Energy"; "Engage"; "Engine";
            "Enough"; "Ensure"; "Entire"; "Entity";
            "Equity"; "Escape"; "Estate"; "Ethnic";
            "Exceed"; "Except"; "Excess"; "Expand";
            "Expect"; "Expert"; "Export"; "Extend";
            "Fabric"; "Facing"; "Factor"; "Failed";
            "Fairly"; "Fallen"; "Family"; "Famous";
            "Father"; "Fellow"; "Female"; "Figure";
            "Filing"; "Finger"; "Finish"; "Fiscal";
            "Flight"; "Flying"; "Follow"; "Forced";
            "Forest"; "Forget"; "Formal"; "Format";
            "Former"; "Foster"; "Fought"; "Fourth"; 
            "French"; "Friend"; "Future"; "Garden";
            "Gather"; "Gender"; "German"; "Global";
            "Golden"; "Ground"; "Growth"; "Guilty";
            "Gabble"; "Gadget"; "Gainly"; "Gallop";
            "Gamble"; "Gamely"; "Gazing"; "Geneva";
            "Gently"; "Giggle"; "Ginger"; "Girdle";
            "Gladly"; "Glazed"; "Glitch"; "Gloomy";
            "Glowed"; "Gluten"; "Goggle"; "Gossip";
            "Graded"; "Grains"; "Grassy"; "Grater";
            "Gravel"; "Grease"; "Greedy"; "Groove";
            "Grudge"; "Guided"; "Guitar"; "Gunner";
            "Gurgle"; "Gabber"; "Gables"; "Gaffes";
            "Gaiety"; "Gainer"; "Gander"; "Gangly";
            "Gawked"; "Gelled"; "Hacker"; "Haggle";
            "Halter"; "Handle"; "Hanger"; "Happen";
            "Harass"; "Harbor"; "Hardly"; "Harmed";
            "Hazard"; "Heated"; "Heaven"; "Herbal";
            "Hereby"; "Heroes"; "Hinder"; "Hinged"; 
            "Hissed"; "Hoarse"; "Homily"; "Hooded"; 
            "Hoofed"; "Hookah"; "Hornet"; "Horrid"; 
            "Horsed"; "Hosted"; "Howard"; "Humble"; 
            "Hunter"; "Hurled"; "Hurray"; "Hurted"; 
            "Hutter"; "Hybrid"; "Hyster"; "Hacked"; 
            "Hagged"; "Hailed"; "Hailer"; "Halers"; 
            "Haling"; "Handed"; "Headed"; "Health"; 
            "Height"; "Hidden"; "Holder"; "Honest";  
            "Impact"; "Import"; "Income"; "Indeed"; 
            "Injury"; "Inside"; "Intend"; "Intent"; 
            "Invest"; "Island"; "Itself"; "Igloos"; 
            "Inning"; "Island"; "Impose"; "Innate"; 
            "Instep"; "Irides"; "Inward"; "Istles"; 
            "Indent"; "Indium"; "Iodize"; "Infant"; 
            "Influx"; "Infamy"; "Insult"; "Injure"; 
            "Invest"; "Invite"; "Indict"; "Inland"; 
            "Insane"; "Ironic"; "Iodine"; "Irises"; 
            "Ironed"; "Irides"; "Issued"; "Innate";   
            "Jersey"; "Junior"; "Jagged"; "Jangle"; 
            "Jargon"; "Jarvis"; "Jersey"; "Jigsaw"; 
            "Jingle"; "Jogged"; "Joiner"; "Joking"; 
            "Jumble"; "Jumped"; "Junker"; "Jungle"; 
            "Junior"; "Jurors"; "Juries"; "Killed";
            "Kettle"; "Keypad"; "Kimchi"; "Kinder"; 
            "Kitten"; "Knight"; "Knives"; "Knocks"; 
            "Knotty"; "Labour"; "Latest"; "Latter"; 
            "Launch"; "Lawyer"; "Leader"; "League"; 
            "Leaves"; "Legacy"; "Length"; "Lesson"; 
            "Letter"; "Lights"; "Likely"; "Linked"; 
            "Liquid"; "Listen"; "Little"; "Living"; 
            "Losing"; "Luxury"; "Mainly"; "Making";
            "Manage"; "Manner"; "Manual"; "Margin"; 
            "Marine"; "Marked"; "Market"; "Master"; 
            "Matter"; "Mature"; "Medium"; "Member"; 
            "Memory"; "Mental"; "Merely"; "Merger"; 
            "Method"; "Middle"; "Miller"; "Mining"; 
            "Minute"; "Mirror"; "Mobile"; "Modern"; 
            "Modest"; "Module"; "Moment"; "Morris"; 
            "Mostly"; "Mother"; "Motion"; "Moving"; 
            "Murder"; "Museum"; "Mutual"; "Myself"; 
            "Monkey"; "Narrow"; "Nation"; "Native"; 
            "Nature"; "Nearby"; "Nearly"; "Nights"; 
            "Nobody"; "Normal"; "Notice"; "Notion"; 
            "Number"; "Nailed"; "Namers"; "Naming"; 
            "Napkin"; "Nectar"; "Needed"; "Object";
            "Obtain"; "Office"; "Offset"; "Online"; 
            "Option"; "Orange"; "Origin"; "Output"; 
            "Oxford"; "Obeyed"; "Oblast"; "Oblong"; 
            "Obsess"; "Obtuse"; "Occult"; "Octane"; 
            "Octave"; "Ocular"; "Oddest"; "Oddity"; 
            "Offend"; "Oiling"; "Okayed"; "Oldest"; 
            "Oldies"; "Olives"; "Omegas"; "Omelet"; 
            "Onions"; "Onside"; "Onward"; "Opaque"; 
            "Openly"; "Operas"; "Opiate"; "Oppose"; 
            "Optics"; "Optime"; "Oracle"; "Orchid"; 
            "Orient"; "Orphan"; "Ounces"; "Outfit"; 
            "Outing"; "Outlaw"; "Outran"; "Outdid"; 
            "Packed"; "Palace"; "Parent"; "Partly"; 
            "Patent"; "People"; "Period"; "Permit"; 
            "Person"; "Phrase"; "Picked"; "Planet"; 
            "Player"; "Please"; "Plenty"; "Pocket"; 
            "Police"; "Policy"; "Prefer"; "Pretty"; 
            "Prince"; "Prison"; "Profit"; "Proper"; 
            "Proven"; "Public"; "Pursue"; "Raised"; 
            "Random"; "Rarely"; "Rather"; "Rating"; 
            "Reader"; "Really"; "Reason"; "Recall"; 
            "Recent"; "Record"; "Reduce"; "Reform"; 
            "Regard"; "Regime"; "Region"; "Relate"; 
            "Relief"; "Remain"; "Remote"; "Remove"; 
            "Repair"; "Repeat"; "Replay"; "Report"; 
            "Rescue"; "Resort"; "Result"; "Retail"; 
            "Retain"; "Return"; "Reveal"; "Review"; 
            "Reward"; "Riding"; "Rising"; "Robust"; 
            "Ruling"; "Safety"; "Salary"; "Sample"; 
            "Saving"; "Saying"; "Scheme"; "School"; 
            "Screen"; "Search"; "Season"; "Second"; 
            "Secret"; "Sector"; "Secure"; "Seeing"; 
            "Select"; "Seller"; "Senior"; "Series"; 
            "Server"; "Settle"; "Severe"; "Signal"; 
            "Signed"; "Silent"; "Silver"; "Simple"; 
            "Simply"; "Single"; "Sister"; "Slight"; 
            "Smooth"; "Social"; "Solely"; "Sought"; 
            "Source"; "Speech"; "Spirit"; "Spoken"; 
            "Spread"; "Spring"; "Square"; "Stable"; 
            "Status"; "Steady"; "Stolen"; "Strain"; 
            "Stream"; "Street"; "Stress"; "Strict"; 
            "Strike"; "String"; "Strong"; "Struck"; 
            "Studio"; "Submit"; "Sudden"; "Suffer"; 
            "Summer"; "Summit"; "Supply"; "Surely"; 
            "Survey"; "Switch"; "Symbol"; "System"; 
            "Talent"; "Taking"; "Taught"; "Tenant"; 
            "Target"; "Tender"; "Tennis"; "Thanks"; 
            "Theory"; "Thirty"; "Though"; "Threat"; 
            "Thrown"; "Ticket"; "Timely"; "Timing"; 
            "Tissue"; "Toward"; "Travel"; "Treaty"; 
            "Trying"; "Twelve"; "Twenty"; "Uglier"; 
            "Upcome"; "Update"; "Upheld"; "Uplift"; 
            "Upload"; "Upmost"; "Uproar"; "Uproot"; 
            "Urchin"; "Urinal"; "Urgent"; "Utmost"; 
            "Unique"; "Unless"; "Useful"; "Unlike"; 
            "United"; "Unable"; "Vacant"; "Vacate"; 
            "Vacuum"; "Vainly"; "Valley"; "Valors"; 
            "Valued"; "Values"; "Vamped"; "Vandal"; 
            "Vapors"; "Varies"; "Varied"; "Veggie"; 
            "Veiled"; "Velour"; "Verify"; "Vessel"; 
            "Vigors"; "Vigour"; "Vipers"; "Victim"; 
            "Visual"; "Versus"; "Vision"; "Volume"; 
            "Walker"; "Wealth"; "Weekly"; "Weight"; 
            "Window"; "Winner"; "Winter"; "Within"; 
            "Wonder"; "Worker"; "Writer"; "Yellow"; 
            "Yachts"; "Yapper"; "Yearly"; "Yogurt";
        ];     
            
    }

}
